config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 10 }
  
end

app/controllers/.rb
class TasksController < ApplicationController
  def index
    @tasklists = Task.all
  end

  def show
    @tasklists = Task.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
   before_action :set_tasklist, only: [:show, :edit, :update, :destroy]
  def index
    @tasklists = Task.all
  end

  def show
  end

  def new
    @tasklist = Task.new
  end

  def create
     @tasklist = Task.new(tasklist_params)

    if @tasklist.save
      flash[:success] = 'Tasklist が正常に投稿されました'
      redirect_to @tasklist
    else
      flash.now[:danger] = 'Tasklist が投稿されませんでした'
      render :new
    end
  end

  def edit
  end

  def update
    if @tasklist.update(tasklist_params)
      flash[:success] = 'Tasklist は正常に更新されました'
      redirect_to @tasklist
    else
      flash.now[:danger] = 'Tasklist は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @tasklist.destroy

    flash[:success] = 'Tasklist は正常に削除されました'
    redirect_to tasks_url
  end
  
private

  def set_tasklist
    @tasklist = Task.find(params[:id])
  end
  
  # Strong Parameter
  def tasklist_params
    params.require(:task).permit(:content, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_flash_tasklists.html.erb
<% flash.each do |tasklist_type, tasklist| %>

  <div class="alert alert-
<%= tasklist_type %>
">
<%= tasklist %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Tasklist</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li>
<%= link_to  '新規タスクの投稿', new_task_path %>
</li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Tasklist</title>
<%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    
<%= render 'layouts/navbar' %>

    <div class="container">
      
<%= render 'layouts/flash_tasklists' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(tasklist) do |f| %>

<% if tasklist.errors.any? %>

    <div id="error_explanation">
      <ul>
        
<% tasklist.errors.full_messages.each do |tasklist| %>

          <li>
<%= tasklist %>
</li>
        
<% end %>

      </ul>
    </div>
  
<% end %>

  <div class="col-xs-12 col-md-offset-2 col-md-8 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
    <div class="form-group">
<%= f.label :status, 'ステータス' %>
<%= f.text_field :status, class: 'form-control' %>
    </div>
    <div class="form-group">
<%= f.label :content, 'タスクリスト' %>
<%= f.text_field :content, class: 'form-control' %>
    </div>
<%= f.submit '投稿', class: 'btn btn-primary' %>
<br>
<%= link_to '一覧に戻る', tasks_path %>
</div>
<% end %>

app/views/tasks/edit.html.erb
<h1>id: 
<%= @tasklist.id %>
 のタスクリスト編集ページ</h1>

<%= render 'form', tasklist: @tasklist %>

<%= link_to '一覧に戻る', task_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<ul>
  
<% @tasklists.each do |tasklist| %>

    <li>
<%= link_to tasklist.id, tasklist %>
 : 
<%= tasklist.status %>
 > 
<%= tasklist.content %>

</li>
  
<% end %>

</ul>

<%= link_to '新規タスクの投稿', new_task_path %>

app/views/tasks/new.html.erb
<h1>タスクリスト新規作成ページ</h1>

<%= render 'form', tasklist: @tasklist %>

app/views/tasks/show.html.erb
<h1>id = 
<%= @tasklist.id %>
 のタスク詳細ページ</h1>

<p>ステータス:
<%= @tasklist.status %>
</p>
<p>タスクリスト:
<%= @tasklist.content %>
</p>

<%= link_to '一覧に戻る', tasks_path %>

<%= link_to 'このタスクリストを編集する', edit_task_path(@tasklist) %>

<%= link_to 'このタスクリストを削除する', @tasklist, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>